---
title: "Weekly Questions and Answers"
author: "Econ 190: Economics of Health Care Markets"
date: "Last Update: 4/8/2020"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 1
    theme: darkly
    number_sections: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate, readr, readxl, hrbrthemes,
               scales, gganimate, gapminder, gifski, png, tufte, plotly, OECD,
               ggrepel)

```

# Overview 
Here, I've compiled some of the most common/relevant questions from your weekly submissions, along with some of our collective responses from class. The goal is that this will serve as a reference throughout the semester and help document all of discussions over the next several weeks.

# Private Insurance and Access {.tabset}

## Questions
1. What percentage of people in the United States have private health insurance? How do private insurance companies cover their customers? Under what circumstances does your job cover health insurance? In general, what types of jobs offer it?
2. How does the Affordable Care Act affect individuals getting private health insurance? Why was the policy that large companies must provide health insurance through a private company originally created? How is private insurance regulated and how does it compete with government-funded insurance companies? 
3. What are different types of plans or options that are available to people from most health insurance providers? How do coverage plans vary vs. how is it streamlined across employers? How do private insurance plans differentiate themselves? How does [private health insurance] make itself accessible to those with limited incomes?
4. Because those with private insurance are limited to the hospitals within network, are people with Medicare or Medicaid limited to specific hospitals?
5. I wonder if there is communication between the large healthcare companies to communicate on pricing. 
6. If the government spends so much money on healthcare, why can't more surgeries/ procedures be covered in the insurance?
7. How could the private insurance market shift towards making healthcare more accessible for those who can't afford insurance? 
8. How would Medicare for All or Public Option healthcare plans change the issue of limited coverage in insurance plans? What will the role of the private sector be if the democratic Medicare-for-all proposals are put in action?
9. What is the best way to remedy the issue caused by the prevalence of private health insurance in the Untied States? 

## Answers
1. What percentage of people in the United States have private health insurance? How do private insurance companies cover their customers? Under what circumstances does your job cover health insurance? In general, what types of jobs offer it? <br>

In 2018, about 50% of people received insurance through their employer, 6% of people purchased insurance directly from a plan (e.g., through the ACA exchange), 20% received insurance from Medicaid, 14% through Medicare, and 9% remained uninsured. The ACA introduced requirements for large employers to offer health insurance coverage, but historically, there have been strong incentives in place to encourage employer-provided insurance. For example, a dollar in health insurance coverage is not taxed, so it is worth more than a dollar in salary (for some workers).

Private insurance "coverage" simply means that the insurer agrees to pay some portion of your health care costs. That portion will vary by plan and may also vary by provider (i.e., the insurer may negotiate a better rate at one hospital versus another).


2. How does the Affordable Care Act affect individuals getting private health insurance? Why was the policy that large companies must provide health insurance through a private company originally created? How is private insurance regulated and how does it compete with government-funded insurance companies?<br>

The ACA created the health insurance exchanges, which is essentially a set of rules and subsidies to help create a "market" for private health insurance when people don't already receive health insurance through some other option (e.g., employer, Medicare, Medicaid). Because private insurers and people were scared about the possiblity of losing their existing insurance plan, the ACA also had policies to maintain the current employer-sponsored plans. That's partly why the ACA mandates large employers to offer health insurance.

There are no major government-funded insurance "companies" but there are government insurance programs such as Medicare and Medicaid. These programs compete with private insurance in a couple of ways that we'll discuss more throughout the semester.


3. What are different types of plans or options that are available to people from most health insurance providers? How do coverage plans vary vs. how is it streamlined across employers? How do private insurance plans differentiate themselves? How does [private health insurance] make itself accessible to those with limited incomes?<br>


The ACA established a set of minimum essential benefits, which are coverage requirements that insurers must maintain in order to be eligible for subsidies. Employer-sponsored insurance also has to meet these requirements, otherwise the employer will not meet the requirement for offering health insurance and be penalized accordingly. But even among the minimum essential benefits, there is a lot of variation in monthly premiums, deductibles, copayments, coinsurance, networks, and prescription drug formularies. There is also variation in customer service and the extent to which insurers deny certain claims (e.g., because a given procedure wasn't justified based on the coding in the claim). 



4. Because those with private insurance are limited to the hospitals within network, are people with Medicare or Medicaid limited to specific hospitals?<br>

Traditional Medicare has no network requirements - patients can go to any hospital or physician they choose. The same is true for traditional Medicaid. However, physicians can (and do) refuse new patients if they are already at capacity, and there is some research showing that Medicaid patients have a particularly hard time making appointments with certain types of physicians (like primary care physicians). Also, a large share of Medicare (over 30%) patients actually receive health insurance through a private insurer via Medicare Advantage. Many states now also use private insurers to cover their Medicaid patients. So in those instances, patients often have the same network restrictions that you see in the standard private insurance market.


5. I wonder if there is communication between the large healthcare companies to communicate on pricing.<br>

Not that I'm aware of. Hospitals are extremely reluctant to publish their negotiated prices.


6. If the government spends so much money on healthcare, why can't more surgeries/procedures be covered in the insurance?<br>

I think the US is pretty generous on average when it comes to what procedures someone will be able to get. That said, insurers certainly don't want to spend money if they don't have to, so there are some denials or at least push-back from the insurer until they are satisfied with the documentation. *The Healing of America* is an interesting book that addresses some of these issues, where the author talks about trying to access the health care systems of several different countries.

I also would clarify that it's not "the government" that necessarily spends so much on health care. The US government probably spends a lot less than some other governments, but that's because a big part of health care bills in the US are covered by individuals and employers.


7. How could the private insurance market shift towards making healthcare more accessible for those who can't afford insurance?<br>

There's not much of an incentive for insurers to do this on their own, so it's a classic case in which some form of government involvement could improve outcomes. The ACA tried to do this by offering large subsidies to individuals on the exchanges. It's hard to evaluate how well things have gone because the ACA has been heavily edited since its passage, with some cost sharing subsidies removed entirely.


8. How would Medicare for All or Public Option healthcare plans change the issue of limited coverage in insurance plans? What will the role of the private sector be if the democratic Medicare-for-all proposals are put in action?<br>

It's not clear what anyone means when they say "Medicare-for-all" at this point. Same with a public option. The effects of these things depend crucially on the details of the plans themselves. I think there are ways to implement these ideas without drastically affecting the private insurance market, if that is the goal.


9. What is the best way to remedy the issue caused by the prevalence of private health insurance in the Untied States?<br>

Not sure that private health insurance is, by itself, an "issue". The problems in the US health care system involve access to care and high costs. Our fragmented system with different insurance structures (Medicare, Medicaid, employer-sponsored private insurance, individual private insurance) contributes to these problems, as does a lack of competition among insurers and health care providers, but just the presence of private insurance isn't a culprit as far as I can tell.


# Medicare {.tabset}

## Questions
1.	What are the requirements that allows people to be eligible for Medicare? What are the different parts of a medicare plan and the extent of their coverages? What are the costs associated with it?

2.	What are the consequences of "running out of social security" and what would also be the impact and consequences of expanding coverage so medicare includes all members of society? How is Medicare going to provide care for an increasing population of baby boomers with a disproportionate number of youths in the workforce?

3.	How is the quality of medicare compared to the government provided health insurance used by middle aged people?

4.	If I die before age 65 after paying my social security taxes for a couple of years, I will not be able to benefit from medicare. Will my family be able to claim the taxes I paid?

5.	I would like to further understand how different plans interact with each other, and why certain seemingly necessary benefits did not make the cut into Parts A & B.

6.	How did the Affordable Care Act impact the Medicare Program in general, and specifically the Medicare Advantage Plan? Additionally, what will Medicare probably look like in 20 or 30 years from now?

7.	How much additional economic strain is put on American citizens in the form of taxes to help pay for Medicare, and how does this additional strain compare to the resulting quality of care received by Medicare recipients?

## Answers
1.	What are the requirements that allow people to be eligible for Medicare? What are the different parts of a medicare plan and the extent of their coverages? What are the costs associated with it?<br>

This is more complicated than you might think because Medicare is not just one product. We have four parts: Medicare Parts A, B, C, and D. Everyone who has worked for 10 years and paid Social Security and Medicare payroll taxes during that time will be eligible for Medicare Part A when they turn 65. They can also enroll in Medicare Part B, which requires a monthly premium. This premium is about $140 a month right now. 

People also have to pay a deductible and copayments/co-insurance. The Part A deductible is about $1,400. The first 60 days of inpatient care are covered with this deductible. Beyond that, people have to pay <span>&#36;</span>352 per day in the hospital (this is a copayment). Beyond 90 days in the hospital, beneficiaries can use up to 30 "lifetime reserve" days, at <span>&#36;</span>704 per day. And if those lifetime reserve days are all spent, then inpatient stays beyond 90 days are not reimbursed at all (patient has to pay the full price).



2.	What are the consequences of "running out of social security" and what would also be the impact and consequences of expanding coverage so medicare includes all members of society? How is Medicare going to provide care for an increasing population of baby boomers with a disproportionate number of youths in the workforce?<br>

Not sure what it means to "run out of social security". Once you begin drawing social security benefits, you receive those benefits for life. There could be issues in funding those social security benefits over time, but that would need to be fixed through some change in legislation or additional federal debt. 

Paying for Medicare and other retirement benefits is definitely a concern. Right now, our government doesn't seem to have any solutions for this. They've made some small tweaks, like increasing the "full retirement age". They also keep increasing cost-sharing, with higher copayments, etc. So without any large scale changes, that's probably the easiest way to deal with things.


3.	How is the quality of medicare compared to the government provided health insurance used by middle aged people?<br>

There is no government provided health insurance (other than Medicaid) for middle-aged people. For the most part, I think that people tend to like Medicare.


4.	If I die before age 65 after paying my social security taxes for a couple of years, I will not be able to benefit from medicare. Will my family be able to claim the taxes I paid?<br>

Social Security, yes. But not Medicare. That kind of makes sense because you only see the value of Medicare taxes if you use health care. So Medicare would have the same expenditures whether you die before 65 or you live past 65 but just don't use health care. 



5.	I would like to further understand how different plans interact with each other, and why certain seemingly necessary benefits did not make the cut into Parts A & B.<br>

That's a good question.


6.	How did the Affordable Care Act impact the Medicare Program in general, and specifically the Medicare Advantage Plan? Additionally, what will Medicare probably look like in 20 or 30 years from now?<br>

The ACA did a few things to Medicare and Medicare Advantage. First, it introduced a couple of pay-for-performance programs into Medicare's payment formulas. Second, it closed the "donut hole" in Medicare Part D plans. Third, it increased the Medicare payroll tax for people with sufficiently high incomes. And fourth, it introduced a quality improvement program in Medicare Advantage plans, where payments to insurance companies is tied to their quality ratings.



7.	How much additional economic strain is put on American citizens in the form of taxes to help pay for Medicare, and how does this additional strain compare to the resulting quality of care received by Medicare recipients?<br>

Not sure that "strain" is the right word, but for most people the Medicare payroll tax is 1.45% of income. Employers also match 1.45%, so the total Medicare payroll tax is 2.9%. For individuals making over $200,000, employers have to pay an additional 0.9% Medicare tax for all wages over the 200,000 makr.

Medicare beneficiaries generally receive the same quality of care that someone with employer-provided insurance coverage would receive, as doctors and hospitals don't usually treat these groups of patients differently based on insurance. There are some findings of reduced access to care for Medicaid patients (because Medicaid has very low payment rates), but not so much with Medicare.

## Class discussion

1. How do you measure quality in health care?
2. How big of a deal is Medicare fraud? How do we even define fraud?


# Medicaid {.tabset}

## Questions
1.	Where does the funding for Medicaid come from? Does the private sector have any role? 

2.	What are the exact requirements to receive Medicaid? Can you be covered by both Medicare and Medicaid? What plan options are available to medicaid recipients?

3.	Is Medicaid coverage similar to Medicare part A coverage? Why wasn't medicaid essentially created as a derivative of medicare? 

4.	How did the Affordable Care Act change Medicaid and who qualified to receive coverage?

5.	Why and how does Medicaid coverage vary across states?

6.	Do immigrants (green card holders) have access to Medicaid after they start paying taxes?

7.	How does access for Medicaid patients differ from other insurers as it always pays the lowest rate among payers?

8.	How relevant are fraud issues (like upcoding) within the Medicaid program, and what measures are in place to make sure that hospitals don’t take advantage of people on Medicaid?

9.	Would expansion of federal programs like medicaid to include other groups of people, mainly young adults, from low income backgrounds be beneficial? What would be the broader economic and political impact of such an action?

10.	Can Medicaid apply to anyone? I see one requirement is to be a child or the parent/caretaker of a child. Does that really give the option for anyone with a kid to be medicaid insured? if so how is this different from a universal basic health insurance?


## Answers
1.	Where does the funding for Medicaid come from? Does the private sector have any role? <br>

Medicaid is funded by a combination of state funding with federal "matching". The private sector is involved in facilitating Medicaid insurance coverage (i.e., forming the networks and managing the claims). Not all states parter with private insurers in this way but it is now the predominant way to deliver Medicaid benefits.

2.	What are the exact requirements to receive Medicaid? Can you be covered by both Medicare and Medicaid? What plan options are available to medicaid recipients?<br>

The requirements vary by state but there are some mandatory federal requirements that every state has to satisfy (minimum eligiblity standards). A description of these requirements can be found [here](https://www.medicaid.gov/medicaid/eligibility/index.html). You can definitely receive both Medicare and Medicaid coverage (and many people do). And generally, Medicaid is just a single product without any choice of plans, although again, this can vary by state.

3.	Is Medicaid coverage similar to Medicare part A coverage? Why wasn't medicaid essentially created as a derivative of medicare?<br>

Medicaid and Medicare were introduced at the same time but are intended to cover different populations. One was originally more of a retirement benefit and the other a safety net program. Medicaid coverage is more generous than Medicare Part A, because Medicaid covers hospital services, physician services, prescription drugs, and other things.

4.	How did the Affordable Care Act change Medicaid and who qualified to receive coverage?<br>

The ACA expanded Medicaid coverage criteria to include a broader set of individuals. In particular, Medicaid has always covered low-income families, but has not historically covered low-income individuals or couples without kids. The Medicaid expansion includes such households. BUT...the expansion is voluntary so not all states chose to expand coverage to those people.

5.	Why and how does Medicaid coverage vary across states?<br>

Why - I'm not sure. It's just one of those programs that we've decided should be implemented with significant state discretion. How - the main difference is in eligibility, although there are some differences in the types of health care services covered under Medicaid as well.

6.	Do immigrants (green card holders) have access to Medicaid after they start paying taxes?<br>

I'm not an expert in this area by any means, but my understanding is that "qualified non-citizens (such as green card holders) have a 5-year waiting period." This is from healthcare.gov. So even green card holders must wait 5 years to receive Medicaid benefits. Note also that undocumented immigrants cannot enroll in Medicaid, Medicare, or CHIP (which is a sister program to Medicaid).

7.	How does access for Medicaid patients differ from other insurers as it always pays the lowest rate among payers?<br>

Access differs in that Medicaid patients may find it difficult to make an appointment. Since the price is very low, providers may prioritize higher paying patients when scheduling visits, surgeries, etc.

8.	How relevant are fraud issues (like upcoding) within the Medicaid program, and what measures are in place to make sure that hospitals don’t take advantage of people on Medicaid?<br>

I'm not sure about any specifics, but I suspect that fraud in the form of upcoding is similar in Medicaid as it is with Medicare. Since Medicaid covers nursing home care and other patients with disabilities, there may be more opportunities to take advantage of the program. But I'm not sure what the data say here.


9.	Would expansion of federal programs like medicaid to include other groups of people, mainly young adults, from low income backgrounds be beneficial? What would be the broader economic and political impact of such an action?<br>

Well it certainly costs money to provide insurance to more people. But those costs may be offset by spending decreases in other areas. The literature is a little mixed here. Expanding insurance coverage certainly helps avoid financial risk of negative health events, so that's probably a good thing, particularly among a group of people least likely to absorb such a financial shock.

10.	Can Medicaid apply to anyone? I see one requirement is to be a child or the parent/caretaker of a child. Does that really give the option for anyone with a kid to be medicaid insured? if so how is this different from a universal basic health insurance?<br>

No - there are income requirements as well. For example, in Georgia, children under age 1 are covered if the family income is below 250% of the federal poverty line (about $53,000 per year for a family of 3). The income requirements are more stringent as children get older.

## Class discussion

1. What is a block grant program? 
2. What are some pros and cons of moving Medicaid to a block grant program?


# The ACA {.tabset}

## Questions
1.	How did the ACA come about and what were the initial regulations and funding like? 

2.	How does imposing taxes on some health insurance providers make costs lower to people? (if that creates higher costs for the insurance provider, wouldn't that, in turn, raise prices to consumers?)

3.	How have the ACA’s policies for health care been changed in recent years by the Trump Administration? Was the Affordable Care Act completely repealed by the Trump administration? 

4.	What problems in the US health care system did the ACA fail to address?

5.	How effective was the ACA at providing individuals with pre-existing conditions affordable health insurance? What demographic of people did the ACA affect the most in terms of access to healthcare?

6.	How was the ACA received by private healthcare providers? How did it impact private insurance companies?

7.	If a Medicare for all Bill Passes in the future, what aspects of the Affordable Care Act will be preserved? 

8.	If employers find it cheaper to pay a tax penalty instead of providing health insurance for their employees, wouldn't a lot of employees lose health insurance because of the ACA?

## Answers
1.	How did the ACA come about and what were the initial regulations and funding like?<br>

The starting point for the ACA was a recognition that a "brand new" health care system was not politically feasible. The law wouldn't pass if they created a new system from scratch. So instead, they made a decision to take the existing system, identify key areas needing major improvements, and work specifically on those areas. The law itself became (and remains) extremely politically polarizing, although many of the policies in the law were actually bipartisan in nature.

2.	How does imposing taxes on some health insurance providers make costs lower to people? (if that creates higher costs for the insurance provider, wouldn't that, in turn, raise prices to consumers?)<br>

There are no major new taxes on insurance companies as part of the ACA. There are lots of regulations on the plans they have to offer and how they price their plans, but no specific new taxes that insurers have to pay that I'm aware of.


3.	How have the ACA’s policies for health care been changed in recent years by the Trump Administration? Was the Affordable Care Act completely repealed by the Trump administration?<br>

The ACA has **not** been repealed. The Trump administration has removed some aspects of the law or simply refused to support or enforce the law. For example, the Trum administration severely cut funding for "navigators", which are federally funded positions to provide support in selecting a health insurance plan on the exchanges. The administration has also cut some subsidies to insurers, and they dropped the individual mandate penalty down to $0 (effectively removing the mandate). But all of these things have been done with some political maneuvering. For example, the change in the individual mandate penalty was part of a tax bill (not directly part of a new health bill). Other changes have been through executive order.


4.	What problems in the US health care system did the ACA fail to address?<br>

This is maybe not a failure of the ACA since it didn't try to fix this...but one major issue in U.S. health care is our very fragmented delivery and payment system. In acheiving some other goals, the ACA may have actually made this part of the system worse.


5.	How effective was the ACA at providing individuals with pre-existing conditions affordable health insurance? What demographic of people did the ACA affect the most in terms of access to healthcare?<br>

Very - the uninsured rate dropped dramatically after the ACA. I'm not sure how much of that was specifically among people with pre-existing conditions, but those types of people where disproportionately uninusured before the ACA, so my guess is they constitute a good portion of the newly insured after the ACA.

6.	How was the ACA received by private healthcare providers? How did it impact private insurance companies?<br>

That's a good question. I think most private insurers have learned to do relatively well on the exchanges. There were some growing pains to predict the risk pool of patients and set an appropriate price, but at this point things have stabalized for the majority of counties (not all counties though...some places in Tennessee are having a hard time with premium growth). If insurers weren't doing well, they would leave the market, and we just don't see much of that happening anymore.

7.	If a Medicare for all Bill Passes in the future, what aspects of the Affordable Care Act will be preserved?<br>

I don't see how something like "Medicare for All" could coexist with the ACA. They would have to scrap the ACA and write a new bill. Perhaps some of the ACA is included in the new bill as well, but it would be really hard to keep the ACA in tact while also pursuing a sweeping change like Medicare for All.

8.	If employers find it cheaper to pay a tax penalty instead of providing health insurance for their employees, wouldn't a lot of employees lose health insurance because of the ACA?<br>

The monetary penalty for employers to not offer health insurance (large employers are the only ones subjected to the penalty) is substantial, and there's a labor market effect in that employees still expect insurance through their employer. So we haven't seen this happen at any kind of large scale. There is some anecdotal evidence of large employers changing the nature of some jobs (moving from full time to part time) in order to avoid offering health insurance, but on average, this has not been a common strategy among employers.


# Hospital pricing {.tabset}

## Questions
1.	How is hospital pricing regulated and determined? Does the government have some say in how much they charge patients and insurance companies?

2.	If not competition, what drives the high prices in hospitals? Are increasing labor costs the primary source of why hospital prices continue to rise, or is it other fixed/variable costs that cause this?

3.	What, if any, impact do the prices of pharmaceutical drugs have on hospital pricing?

4.	What can the government do to foster competition between hospitals to lower pricing? What will this do to quality of care? What efforts are legislators making to try and lower hospital prices? Or is it not something they would be able to regulate effectively?

5.	What determines the disparity in hospital prices among different hospitals?

6.	How much does a doctor's pay depend on the number of operations or the money paid by patients and their insurance providers? Are insurance providers creating an incentive to drive prices higher if patients don't have to cover a large portion of the cost?

7.	What areas could hospitals cut costs in to save money without decreasing the quality of care? Why they don't make an effort to cut costs in these areas?

## Answers
1.	How is hospital pricing regulated and determined? Does the government have some say in how much they charge patients and insurance companies?<br>

Not much. The government has a lot of say in Medicare and Medicaid prices, but not much in hospital prices. That said, hospital prices are negotiated with private insurance companies, so hospitals can't unilaterally set the price. But in practice, prices are still very high.


2.	If not competition, what drives the high prices in hospitals? Are increasing labor costs the primary source of why hospital prices continue to rise, or is it other fixed/variable costs that cause this?<br>

Competition would tend to drive prices down. We have very little competition in the U.S. health care system, and so we have very little downward pressure on prices. Our system is *designed* as a market-based health care system, but the "market" is extremely concentrated and therefore doesn't obtain some of the outcomes we would expect in a more competitive system.

3.	What, if any, impact do the prices of pharmaceutical drugs have on hospital pricing?<br>

My guess is not much. The bulk of pharmaceutical drugs aren't administered in a hospital and so high pharma prices don't tend to pass down into hospital prices. 

4.	What can the government do to foster competition between hospitals to lower pricing? What will this do to quality of care? What efforts are legislators making to try and lower hospital prices? Or is it not something they would be able to regulate effectively?<br>

There are lots of things the government can do. Some things are obvious like removing certificate of need laws, allowing federal oversight of proposed mergers, and changing laws regarding enforceability non-compete contracts.


5.	What determines the disparity in hospital prices among different hospitals?<br>

One big factor is competition in local markets and differential market power within markets. For example, Emory University hospital is a bigger player in Atlanta and can probably negotiate a higher price for the same insurer than some other smaller hospital (this is just speculation, I don't know this to be true).


6.	How much does a doctor's pay depend on the number of operations or the money paid by patients and their insurance providers? Are insurance providers creating an incentive to drive prices higher if patients don't have to cover a large portion of the cost?<br>

For a private practice, physician pay is determined solely by the revenue from their practice, which means money received from insurers and patients for their services. For salaried physicians (members of a large group practice or those employed by hospitals), pay is related to these services but not directly tied to quantity of services provided. 
The fact that patients may not have to pay much at the point of care could introduce some aspect of moral hazard or "overuse" of some services. But this dynamic really only applies to the short run (i.e., within the year in which my insurance policy is fixed). Patients still pay their premiums, so patients have to pay for higher prices in the medium and long term.

7.	What areas could hospitals cut costs in to save money without decreasing the quality of care? Why they don't make an effort to cut costs in these areas?<br>

We talked about some examples of clear overuse where some physicians are using way more of a very specific product relative to their peers. But more generally, there is very little incentive to cut costs from the hospital's perspective. 


# Spending and "Waste" {.tabset}

## Questions

1.	What is the most wasted component in US healthcare? How much money goes to "waste" per year in the US?

2.	Does the federal government have any control in limiting wasteful spending? If so, how would these policies be enforced?

3.	Why does wasteful spending happen in healthcare when its cost is already expensive?

4.	Do healthcare providers make profits from "waste" off patients?

5.	What are the most popular ideas to remove wasteful spending (in the health care market) under a Medicare-for-All type plan, and how effective would these methods likely be?

6.	How did a system so wasteful come to be? Are there any incentives on the part of hospitals and insurance companies to decrease their waste, and if so, why does wasteful spending remain so prevalent?

7.	Would moving to a single payer system reduce administrative costs and complexity which constitutes a major part of waste in the US healthcare system?

## Answers
1.	What is the most wasted component in US healthcare? How much money goes to "waste" per year in the US?<br>

The general estimate is that as much as 30% of our health care expenditures are "waste". A big part of this is in administrative costs, some smaller portion is in "overtreatment", and even smaller portions are in "fraud" and physician salaries.

2.	Does the federal government have any control in limiting wasteful spending? If so, how would these policies be enforced?<br>

Somewhat. Through our payment policies, we can encourage more efficient delivery. We also have several policies to reduce "fraud", which is clearly an area of waste.


3.	Why does wasteful spending happen in healthcare when its cost is already expensive?<br>

The biggest areas of waste (administrative waste and overtreatment) come from the system itself. We encourage more care whenever possible in the way we pay for things, and our extremely fragmented insurance and delivery system introduces a lot of administrative issues into the system. It costs money to deal with these administrative complexities, and those costs are passed down in the form of higher prices.

4.	Do healthcare providers make profits from "waste" off patients?<br>

If we're talking about "waste" in the form of additional treatment for which the marginal benefit exceeds the marginal cost, then yes. Hospitals still get paid for that and so they are making more money.


5.	What are the most popular ideas to remove wasteful spending (in the health care market) under a Medicare-for-All type plan, and how effective would these methods likely be?<br>

The biggest area of reduction is in administrative waste. By moving to a single health care plan or single umbrella structure, the administrative issues should simplify.

6.	How did a system so wasteful come to be? Are there any incentives on the part of hospitals and insurance companies to decrease their waste, and if so, why does wasteful spending remain so prevalent?<br>

We have very little cost-saving incentives in our system. Most of the incentives are to do more...very little incentive to do less or cut costs.


7.	Would moving to a single payer system reduce administrative costs and complexity which constitutes a major part of waste in the US healthcare system?<br>

It would definitely reduce administrative costs. That's one area where there is agreement among most people in this debate. There's still some disagreement as to *how much* of a reduction we could expect. 


# Inequalities {.tabset}

## Questions
1.	What types of inequalities are there and are there any laws that protects people from them in the healthcare system?

2.	To what extent do the public insurance options effectively bridge the gap of inequality in healthcare? Have there been successful efforts to close this gap?

3.	How expensive would it be to provide health care to those who make too much for Medicaid but too little to afford their own plan?

4.	 If a situation where a foreign national arrives in a hospital and they are unable to pay will they be treated?

5.	 How does the structure of the U.S. health care system promote/affect income inequality and health disparities? How well did the ACA do in addressing these?

6.	Would elimination of corporate sponsored plans and introduction of “Medicare for all” reduce healthcare inequality in the US?

## Answers
1. What types of inequalities are there and are there any laws that protects people from them in the healthcare system?<br>

I think the biggest inequality is in the limited access to health care due to income constraints. If someone is uninsured or "underinsured", and they have a major chronic condition such as diabetes, they may not receive the necesssary treatment. In other words, higher income people can extend their lives and maintain their health moreso than lower income people due to more generous health insurance.

2. To what extent do the public insurance options effectively bridge the gap of inequality in healthcare? Have there been successful efforts to close this gap?<br>

For states with broad Medicaid coverage, I would say yes. It hasn't closed the gap because there are other issues that aren't directly attributable to health insurance, but expanding Medicaid has certainly helped. Medicare has similarly helped among those over 65.


3. How expensive would it be to provide health care to those who make too much for Medicaid but too little to afford their own plan?<br>

These types of households are directly addressed as part of the ACA exchanges. In the exchanges, there are subsidies determined partly on income, so housholds with less income receive a higher subsidy.


4. If a situation where a foreign national arrives in a hospital and they are unable to pay will they be treated?<br>

I think that depends on what needs to be done. Hospitals must "stabalize" anyone coming in, regardless of citizenship status. Some hospitals may also be more or less generous, which is just a hospital-specific policy. 


5. How does the structure of the U.S. health care system promote/affect income inequality and health disparities? How well did the ACA do in addressing these?<br>

We rely on private insurance through employers for most people, which necessarily leaves some people out of the "good" health insurance market. People left out of that market include part-time workers, independent contractors, self-employed workers, or the unemployed. Some of these people may be eligible for Medicaid, but as we've discussed, Medicaid eligibility varies by states. The ACA attempted to help by expanding Medicaid and creating a private insurance exchange for people ineligible for Medicaid but not covered by the employer plans.


6. Would elimination of corporate sponsored plans and introduction of “Medicare for all” reduce healthcare inequality in the US?<br>

I think there's little question that such a policy would reduce inequality. The question is how much would this cost and how much would the system differ for people doing "well" in the current system. 

If a Medicare for all system doesn't change payments, then it would be very expensive. If it reduces payments to improve access to care, then how much would that affect quality of care and future innovation?


## Class Discussion
1. How do we pay for health insurance now? [KFF Employer Health Benefits Survey](https://www.kff.org/report-section/ehbs-2019-summary-of-findings/).


2. Let's work with the online cost/utilization tool. How do these different dimensions affect spending?

3. What about quality?

# Medicare-for-all 

Questions and our virtual class discussion are all available at the following link: [Zoom Class, Wednesday March 25](https://drive.google.com/file/d/14za228L6hS82wIeMzV_7em9dFfGPrzjc/view?usp=sharing).

# Future of the ACA

Questions and our virtual class discussion are all available at the following link: [Zoom Class, Wednesday April 1](https://drive.google.com/open?id=1SBf4oAFCZuuv8FtDyGUsBJhOQY7tgRuK).

# Surprise Billing

Questions and our virtual class discussion are all available at the following link: [Zoom Class, Wednesday April 8](https://drive.google.com/open?id=19E6AW4XCowCznpCZjQXsXVzf4zLpWQix).